services:
  db:
    image: postgres
    container_name: postgres_db
    restart: no
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: CatS_user
      POSTGRES_PASSWORD: CatS_test
      POSTGRES_DB: CatS
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: CatS_app
    command: uvicorn main:app --host 0.0.0.0 --reload
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://CatS_user:CatS_test@db:5432/CatS
    volumes:
      - ./backend/app:/app
    

volumes:
  db-data: